apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev

resources:
- ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
- name: backend
  count: 1
- name: frontend
  count: 1

images:
- name: myregistry/ecommerce-backend
  newTag: develop-latest
- name: myregistry/ecommerce-frontend
  newTag: develop-latest

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "128Mi"
  target:
    kind: Deployment
    name: backend

secretGenerator:
- name: postgresql-secret
  literals:
  - password=devpassword123