apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

resources:
- ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
- name: backend
  count: 2
- name: frontend
  count: 2

images:
- name: myregistry/ecommerce-backend
  newTag: staging-v1.2.0
- name: myregistry/ecommerce-frontend
  newTag: staging-v1.2.0

secretGenerator:
- name: postgresql-secret
  literals:
  - password=stagingpassword456
