apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgresql.yaml
- redis.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: ecommerce
  app.kubernetes.io/managed-by: argocd